name: Build docker image

on:
  push:
    branches:
    - master
    - 4.x

    tags:
    - '*'

  pull_request:

env:
  DRUPAL9: 9.1.2
  DRUPAL8: 8.9.12
  DRUPAL7: 7.77


  # keep a few lines to avoid conflicts.
  BASE_IMAGE_STABILITY_TAG: 4.22.0

jobs:
  # drupal 9
  drupal-9-80:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL9 }}
        php_ver: '8.0'
        tags: 9-8.0,9-8,9,latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 9
  drupal-9-74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL9 }}
        php_ver: '7.4'
        tags: 9-7.4,9-7
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 9
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
  drupal-9-73:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL9 }}
        php_ver: '7.3'
        tags: 9-7.3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 9
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
  # drupal 8
  drupal-8-74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL8 }}
        php_ver: '7.4'
        tags: 8-7.4,8-7,8
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 8
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
  drupal-8-73:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL8 }}
        php_ver: '7.3'
        tags: 8-7.3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 8
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
  drupal-8-72:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL8 }}
        php_ver: '7.2'
        tags: 8-7.2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 8
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
  # drupal 7
  drupal-7-74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL7 }}
        php_ver: '7.4'
        tags: 7-7.4,7-7,7
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
  drupal-7-73:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL7 }}
        php_ver: '7.3'
        tags: 7-7.3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
  drupal-7-72:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.DRUPAL7 }}
        php_ver: '7.2'
        tags: 7-7.2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
